// export const envConfig = {
//     NOTION_API_BASE_URL : process.env.NEXT_PUBLIC_NOTION_API_BASE_URL,
//     SPLITBEE_API_BASE_URL: process.env.NEXT_PUBLIC_SPLITBEE_API_BASE_URL,
//     NOTION_BLOG_TABLE_ID: process.env.NEXT_PUBLIC_NOTION_BLOG_TABLE_ID,
// }